name: Epic
description: A large feature or project
type: Epic
body:
  - type: textarea
    attributes:
      label: Goal
      description: "One sentence on what the end state looks like, highlighting the difference with the current state. No how or why."
      placeholder: "All customer-related authentication and authorization managed via Keycloak."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: "A detailed description of the epic."
      placeholder: "Describe the epic in as much detail as possible."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation and Context
      description: "Why is this epic useful or necessary?"
      placeholder: "Explain why this epic is needed"
    validations:
      required: false
