name: Epic
description: A large feature or project
type: Epic
body:
  - type: textarea
    attributes:
      label: Description
      description: "A detailed description of the epic."
      placeholder: "Describe the epic in as much detail as possible."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation and Context
      description: "Why is this epic useful or necessary?"
      placeholder: "Explain why this epic is needed"
    validations:
      required: false
