name: Feature Request
description: Suggest a new feature for this project
projects: ["viio-io/4"]
labels: ["type:feature"]
body:
  - type: markdown
    attributes:
      value: "Thanks for taking the time to submit a feature request!"
  - type: textarea
    attributes:
      label: Feature Description
      description: "A detailed description of the feature you're requesting."
      placeholder: "Describe the feature in as much detail as possible."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why this Feature?
      description: "Explain why this feature would be beneficial for the project."
      placeholder: "Why do you think this feature is needed?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Possible Implementation
      description: "If you have ideas about how the feature could be implemented, please share them here."
      placeholder: "Suggest how this feature might be implemented, if you have ideas."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: "Provide any additional context or screenshots about the feature request here."
      placeholder: "Add any other context or screenshots about the feature request."
    validations:
      required: false
