name: Spike Task
description: Create a spike task for investigation or research
projects: ["viio-io/4"]
labels: ["type:spike"]
body:
  - type: markdown
    attributes:
      value: "Thank you for initiating a spike task. Please provide detailed information to help guide the investigation."
  - type: textarea
    attributes:
      label: Objective
      description: "A clear and concise statement of what this spike aims to investigate or accomplish."
      placeholder: "What is the goal of this spike?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Background/Context
      description: "Any background information or context relevant to this spike."
      placeholder: "Provide any relevant background or context."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Specific Questions or Areas of Focus
      description: "List any specific questions or areas that need to be focused on during the investigation."
      placeholder: "What specific areas should this investigation focus on?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Outcomes
      description: "Describe the expected outcomes or deliverables from this spike."
      placeholder: "What are the expected outcomes of this spike?"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Timeframe
      description: "If applicable, specify the timeframe or deadline for completing this spike."
      placeholder: "Specify a timeframe or deadline."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Resources
      description: "Include any additional resources (links, documents, etc.) that may aid in this spike."
      placeholder: "List any additional resources here."
    validations:
      required: false
