name: Support Request
description: Submit a support request or inquiry
title: "[SUPPORT]: "
projects: ["viio-io/6"]
labels: ["type:support"]
body:
  - type: markdown
    attributes:
      value: "Thank you for reaching out for support. Please provide as much detail as possible to help us assist you effectively."
  - type: input
    attributes:
      label: Customer Name or ID
      description: "Please provide the customer name or identification number."
      placeholder: "Enter customer name or ID"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issue Description
      description: "Describe the issue or question you're encountering."
      placeholder: "Provide a detailed description of the issue."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Impact and Urgency
      description: "Describe the impact of this issue on your work and its urgency."
      placeholder: "Explain the impact and how urgent the issue is."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps to Reproduce (if applicable)
      description: "If your issue is reproducible, please list the steps taken to reproduce it."
      placeholder: "1. Go to '...'\n2. Click on '....'\n3. Notice the issue..."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Information
      description: "Any additional information, context, or relevant details not covered above."
      placeholder: "Add any other information or details here."
    validations:
      required: false
